---
- name: Checks sync status and health of all ArgoCD applications installed in cluster
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check health of argo applications
      ansible.builtin.include_tasks: tasks/check_argo_health.yml
