---
- name: Decide whether to load secrets
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: pattern_settings

  tasks:
    - name: Check values-global to see if secret loading is explicity disabled
      ansible.builtin.set_fact:
        secret_loader_disabled: "{{ values_global.global.secretLoader.disabled | default(false) | bool }}"

    - name: Load secrets (when enabled)
      ansible.builtin.include_role:
        name: load_secrets
      when: not secret_loader_disabled

    - name: Print secret loading disabled message
      ansible.builtin.debug:
        msg: |
          Secrets loading is currently disabled. To enable, update the value of ''.global.secretLoader.disabled' in 'values-global.yaml' to 'false'.
      when: secret_loader_disabled
