---
- name: Decide whether to load secrets
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: pattern_settings

  tasks:
    - name: Check values-global to see if secret loading is explicity disabled
      ansible.builtin.set_fact:
        secret_loader_disabled: "{{ values_global.global.secretLoader.disabled | default(false) | bool }}"

    - name: Load secrets (when enabled)
      when: not secret_loader_disabled
      block:
        - name: Announce secrets loading
          ansible.builtin.shell: |
            printf "==> Loading secrets (this may take several minutes)...\n" > /dev/tty

        - name: Process secrets via role
          ansible.builtin.include_role:
            name: load_secrets
      rescue:
        - name: "Print debugging command when secrets loading fails"
          ansible.builtin.shell: |
            printf "==> ERROR: Secret loading failed {{ ansible_failed_result.msg | default('Unknown error occurred') }}\n" > /dev/tty
            printf "\n" > /dev/tty
            printf "You can run the following command to debug:\n" > /dev/tty
            printf "\n" > /dev/tty
            printf "  ANSIBLE_STDOUT_CALLBACK=default EXTRA_PLAYBOOK_OPTS='-vvv -e hide_sensitive_output=false' ./pattern.sh make load-secrets\n" > /dev/tty

    - name: Print secret loading disabled message
      ansible.builtin.shell: |
        printf "==> Secrets loading is currently disabled. To enable, update the value of .global.secretLoader.disabled in your values-global.yaml to false.\n" > /dev/tty
      when: secret_loader_disabled
