---
name: Ansible unit tests

on: [push, pull_request]

jobs:
  ansible_unittests:
    name: Ansible unit tests
    strategy:
      matrix:
        python-version: [3.11.3, 3.12.6]
        ansible-core: ["2.16.*"]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          path: ansible_collections/rhvp/cluster_utils
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ansible-core=='${{ matrix.ansible-core }}'

      - name: Run make ansible-unittest
        run: |
          cd ansible_collections/rhvp/cluster_utils
          make ansible-unittest
